[package]
name = "rgraphs"
version = "0.3.0"
authors = ["Simon Gasse <sgasse@users.noreply.github.com>"]
edition = "2018"

[lib]
name = "rgraphs"
path = "src/lib.rs"

[[bin]]
name = "rgraphs"
path = "src/main.rs"

[dependencies]
